[package]
name = "dbt-converter"
version = "0.1.3"
edition = "2021"
rust-version = "1.78.0"

[dependencies]
serde_yaml = "0.9"
serde = { version = "1", features = ["derive"] }
regex = { version = "1" }
walkdir = "2"
tempfile = "3"
quary_proto = { path = "../../proto/gen/rust" }

[lib]
