name: pr-checks
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  sqruff-lint:
    name: Lint template with sqruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v3
      - uses: quarylabs/install-sqruff-cli-action@main
      - name: Lint template
        run: sqruff lint .
  prettier-yaml:
    name: Lint/Format YAML with Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npx prettier --check '**/*.yaml'
  quary-compile:
    name: Compile the Quary project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v3
      - uses: quarylabs/install-quary-cli-action@main
      - run: quary compile
