models:
  - name: stg_employees
    description: 'This is a staging model for employees and contains information about the employees of the company.'
    columns:
      - name: employee_id
        description: "This is the employee's unique identifier."
        tests:
          - type: unique
          - type: not_null
      - name: first_name
        description: "This is the employee's first name."
        tests:
          - type: not_null
      - name: last_name
        description: "This is the employee's last name."
        tests:
          - type: not_null
  - name: stg_shop_locations
    description: "This is a staging model for shop locations and contains information about the locations of the company's shops."
    columns:
      - name: id
        description: "This is the shop's unique identifier."
        tests:
          - type: unique
          - type: not_null
      - name: shop_name
        description: "This is the shop's name."
        tests:
          - type: not_null
      - name: latitude
        description: "This is the shop's latitude."
        tests:
          - type: not_null
          - type: gte
            info:
              value: -90
          - type: lte
            info:
              value: 90
      - name: longitude
        description: "This is the shop's longitude."
        tests:
          - type: not_null
          - type: gt
            info:
              value: -180
          - type: lt
            info:
              value: 180
      - name: manager_id
        description: "This is the employee's unique identifier who acts as the shops manager."
        tests:
          - type: not_null
          - type: relationship
            info:
              model: stg_employees
              column: employee_id
  - name: stg_shifts
    description: "This is a staging model for shifts and contains information about the shifts of the company's employees."
    columns:
      - name: employee_id
        description: "This is the employee's unique identifier."
        tests:
          - type: not_null
          - type: relationship
            info:
              model: stg_employees
              column: employee_id
      - name: shop_id
        description: "This is the shop's unique identifier where the shift took place."
        tests:
          - type: not_null
          - type: relationship
            info:
              model: stg_shop_locations
              column: id
      - name: shift_date
        description: 'This is the date of the shift.'
        tests:
          - type: not_null
      - name: shift
        description: 'This is the shift (morning/afternoon) of the day.'
        tests:
          - type: not_null
          - type: accepted_values
            info:
              values: morning,afternoon
